In [1]:
import numpy

ModuleNotFoundError: No module named 'numpy'

In [1]:
import numpy

In [2]:
import numpy as np

In [9]:
a=np.array([(1,2,3),(4,5,6)])

In [5]:
print(a)

[1 2 3]


In [6]:
trans=np.transpose(a)

In [10]:
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
trans=np.transpose(a)

In [12]:
print(trans)

[[1 4]
 [2 5]
 [3 6]]


In [14]:
trans.ravel()

array([1, 4, 2, 5, 3, 6])

In [18]:
trans.reshape(2,3)

array([[1, 4, 2],
       [5, 3, 6]])

In [24]:
ze=np.zeros((1,2))

In [25]:
print(ze)

[[0. 0.]]


In [26]:
ze=np.ones((1,2))

In [27]:
print(ze)

[[1. 1.]]


In [28]:
np.append(trans,ze)

array([1., 4., 2., 5., 3., 6., 1., 1.])

In [32]:
np.random.random((10,10))

array([[0.24021892, 0.52711403, 0.19642809, 0.1217435 , 0.54910944,
        0.16492189, 0.3761195 , 0.73022623, 0.50702129, 0.5309454 ],
       [0.82940173, 0.59830302, 0.8599592 , 0.88143154, 0.31335945,
        0.03155968, 0.91745321, 0.87597543, 0.40416374, 0.93985099],
       [0.00757662, 0.25897596, 0.69357087, 0.88511234, 0.01089495,
        0.78541818, 0.19942783, 0.57906523, 0.7603258 , 0.21802733],
       [0.13574098, 0.70315226, 0.97919222, 0.25961542, 0.75050545,
        0.75182303, 0.32785631, 0.43072853, 0.3553503 , 0.33348931],
       [0.91004591, 0.83922181, 0.04091626, 0.65927226, 0.58227823,
        0.42404933, 0.00555094, 0.90707084, 0.81238393, 0.56161568],
       [0.19645728, 0.92757236, 0.96791143, 0.70249653, 0.95127308,
        0.02520556, 0.21339676, 0.24745751, 0.94876692, 0.00854177],
       [0.23038712, 0.64462807, 0.23021282, 0.28657303, 0.73007732,
        0.61651694, 0.47999079, 0.14322997, 0.12742305, 0.33392982],
       [0.95633213, 0.43855379, 0.0608183

In [33]:
np.append(a,(7,8,9))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.append(a,2)

array([1, 2, 3, 4, 5, 6, 2])